### PR TITLE
Add CSS modules

### PR DESCRIPTION
**Pull request by Chariyski**

### CODE REVIEW

**Comment by aleksandrenko** [comment]
Merge it?

**Comment by Chariyski** [comment]
@aleksandrenko,
If you want you can change the other components ?

**Comment by aleksandrenko** [comment]
I will :), but later.

**Comment by Chariyski** [comment]
@aleksandrenko 
@adrian-bobev 
@kazandjiev 

Ready for :ship:

**Comment by adrian-bobev** [comment]
Cool

**Pull request merged**
